name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
    - name: First interaction
      uses: actions/first-interaction@v1.0.0
      with:
        # Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}
        repo-token: "{{ secrets.GITHUB_TOKEN }}"
        # Comment to post on an individuals first issue
        issue-message: "Thanks for creating an issue. We will take a look ASAP!!"
        # Comment to post on an individuals first pull request
        pr-message: "Thanks for submitting a PR. We will take a look ASAP!!"
